[2023-07-10T02:20:21.151+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_uber_data.extract manual__2023-07-10T02:20:18.846020+00:00 [queued]>
[2023-07-10T02:20:21.158+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_uber_data.extract manual__2023-07-10T02:20:18.846020+00:00 [queued]>
[2023-07-10T02:20:21.159+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-10T02:20:21.179+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): extract> on 2023-07-10 02:20:18.846020+00:00
[2023-07-10T02:20:21.183+0000] {standard_task_runner.py:57} INFO - Started process 252 to run task
[2023-07-10T02:20:21.185+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_uber_data', 'extract', 'manual__2023-07-10T02:20:18.846020+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/etl_uber_data.py', '--cfg-path', '/tmp/tmpb8zft70i']
[2023-07-10T02:20:21.187+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask extract
[2023-07-10T02:20:21.229+0000] {task_command.py:410} INFO - Running <TaskInstance: etl_uber_data.extract manual__2023-07-10T02:20:18.846020+00:00 [running]> on host c718dbe5e804
[2023-07-10T02:20:21.297+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mervyn Frost' AIRFLOW_CTX_DAG_ID='etl_uber_data' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2023-07-10T02:20:18.846020+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-10T02:20:18.846020+00:00'
[2023-07-10T02:20:21.299+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_uber_data.py", line 20, in extract
    df = pd.read_csv(path)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'Desktop/airflow-docker/uber_data.csv'
[2023-07-10T02:20:21.311+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_uber_data, task_id=extract, execution_date=20230710T022018, start_date=20230710T022021, end_date=20230710T022021
[2023-07-10T02:20:21.320+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 3 for task extract ([Errno 2] No such file or directory: 'Desktop/airflow-docker/uber_data.csv'; 252)
[2023-07-10T02:20:21.359+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-10T02:20:21.379+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
